# Generated by Django 4.1.1 on 2022-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pnr', models.IntegerField(null=True)),
                ('trname', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=1)),
                ('status', models.CharField(default='confirmed', max_length=100)),
            ],
        ),
    ]
