# Generated by Django 4.1.1 on 2022-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trname', models.CharField(max_length=100)),
                ('stn', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=25)),
                ('fare', models.IntegerField(null=True)),
            ],
        ),
    ]
