# Generated by Django 4.1.1 on 2022-10-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addstn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationdetails',
            old_name='trname',
            new_name='trnamee',
        ),
    ]
